/*JOINS:
-->IT IS PROCESS OF RETRIVE THE DATA FROM MULTIPLE TABLES SIMULATNESOULY IS KNOWN AS JOINS
-->WHY?? :
---->WHENEVER ATTRIBUTES/COLUMN_NAMES HAS TO BE SELECTED FROM BOTH TABLES WE MUST USE JOINS.*/

/*TYPES OF JOINS
1)CARTENSIAN JOIN/ CROSS JOIN
2)INNER JOIN
3)OUTER JOIN
-->I) LEFT OUTER JOIN
-->II) RIGHT OUTER JOIN
-->III) FULL OUTER JOIN
4)SELF JOIN
5)NATURAL JOIN


1)CARTENSIAN JOIN/ CROSS JOIN:
IT IS USED FOR TABLE1 ALL THE RECORDS ARE MERGED WITH TABLE2 RECORDS
SYNTAX= IT FOLLOWS THE SYNTAX OF ANSI--> AMERIACN NATIONAL STANDERAD INSTITUDE
SYNATX:
SELECT COL_NAEM1,COL_NAME2,....COL_NAMEN
FROM TABLE_NAME
CROSS JOIN TABLE_NAME2; */

/*WQTD ENAME AND DNAME OF EMPLOYEE */
SELECT ENAME, DNAME
FROM EMP
CROSS JOIN DEPT;

/* DRAWBACK:
IN CROSS JOIN WE ARE GETTING BOTH MATCHED RECORD AND UNMATCHED RECORDS WE CALL
 THEM AS ERROR RECORDS THATS THE REASONS WE ARE NOT USING THIS JOIN*/


/*2)INNER JOIN:
IT IS USED TO OBTAIN ONLY MATCHING RECORDS.
RECORDS WHICH HAS PAIR.
-->JOIN CONDITION: 
----->IT IS CONDITION ON WHICH TWO OR MORE TABLES WILL MERGED OR JOIN TOGETHER.
-->SYNTAX OF JOIN CONDITION :
----->TABLE_NAME1.COL_NAME=TABLE_NAME2.COL_NAME;
SYNTAX OF INNER JOIN:
-->SELECT COL_NAME1, COL_NAME2,-------COL_NAMEN
		  FROM TABLE_NAME1 INNER JOIN TABLE_NAME2
          ON <JOIN CONDITION>; 
IF WE NOT PUT JOIN CONDITION IT WORK LIKE CROSS JOIN */


SELECT ENAME, DNAME
FROM EMP INNER JOIN dept
ON EMP.DEPTNO=DEPT.DEPTNO;  


/* WQTD ENAME,JOB.AND LOCATION OF EMP*/
SELECT * FROM EMP;

SELECT ENAME, JOB, LOC
FROM EMP CROSS JOIN DEPT;

SELECT ENAME, JOB, LOC
FROM EMP INNER JOIN DEPT 
ON EMP.DEPTNO = DEPT.DEPTNO;
	
/*WQTD NAME, SALARY, DEPARTMENT NAME OF EMPLOYEE IF EMPLOYEE WORKING IN DNAME SALES */
SELECT ENAME, SAL,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME='SALES';

SELECT * FROM DEPT;

/*WQTD DETAILS OF EMPLOYEE TABLE DETAILS OF DEPARTMENT TABLE IF EMPLOYEES ARE WORKING IN LOCATION NEWYORK*/
SELECT *
FROM EMP INNER JOIN dept
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE LOC='NEW YORK';

SELECT ENAME, DNAME,LOC
FROM EMP INNER JOIN dept
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE LOC='NEW YORK';

/*WQTD NAME,JOB,HIREDATE, DNAME,LOCATION 
IF EMPLOYEE WORKING AS MANAGER AND WORKING IN DEPTNO 20 AND WORKING DNAME RESEARCH*/
SELECT ENAME, JOB, HIREDATE, DNAME,LOC 
FROM EMP INNER JOIN dept
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB='MANAGER' AND DEPTNO=20 AND DNAME='RESEARCH';
-- SHOW THE ERROR  DEPNO IN WHERE CLAUSE IS AMBIGUOUS

SELECT ENAME, JOB, HIREDATE, DNAME,LOC 
FROM EMP INNER JOIN dept
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB='MANAGER' AND EMP.DEPTNO=20 AND DNAME='RESEARCH';
-- correct query

 /*WQTD ENAME, JOB,LOCATION OF EMPLOYEE IF EMPLOYEE
 NAME STARTS WITH A AND GETTING SALARY MORE THAN MARTIN*/
 SELECT ENAME, JOB LOC 
 FROM EMP INNER JOIN DEPT 
 ON EMP.DEPTNO = DEPT.DEPTNO 
 WHERE ENAME LIKE'A%' AND  SAL > ( SELECT SAL
                                   FROM EMP
								   WHERE ENAME='MARTIN')
/* 3)NATURAL JOIN:
IT BEHAVES AS INNER JOIN IF THERE IS RELATIONSHIP EXISTS BETWEEN
TWO TABLES ELSE IT BEHAVES AS CARTISIAN JOIN/CROSS JOIN 
IF THERE IS NO RELATIONSHEEP BETWEEN TWO TABLES:
SYNTAX: NATURAL JOIN
SELECT COL_NAME1,COL_NAME2___ COL_NAMEN
FROM TABLE_NAME1 NATURAL JOIN TABLE_NAME2; */

SELECT ENAME, DNAME
FROM EMP NATURAL JOIN DEPT;

SELECT ENAME, CNAME
FROM EMP NATURAL JOIN CUSTOMER1;


/* 4)SELF JOIN:
-->JOIN THE TABLE BY ITSELF USE THE SELF JOIN
--->WHENEVER DATA HAS TO BE SELECTED FROM SAME TABLE BUT PRESENT IN A DIFFERENT RECORDS WE USE SELF JOIN.
-->SYNTAX: ANSI
---> SELECT VOL_NAME1,COL_NAME2,__COL_NAMEN
     FROM TABLE_NAME T1 JOIN TABLE_NAME T2
     ON <JOIN CONDITION>; */
     
/*WQTD EMPLOYEE NAME AND MANAGER'S NAME OF EMPLOYEE */    
SELECT E1.ENAME, M1.ENAME AS MANAGER
FROM EMP E1 JOIN EMP M1
ON E1.MGR = M1.EMPNO;

/*WQTD EMPLOYEE NAME, EMPLOYEE JOB, MANAGER'S NAME 
MANAGERS JOB OF EMPLOYEE */
SELECT E1.ENAME, E1.JOB, M1.ENAME, M1.JOB 
FROM EMP E1 JOIN EMP M1
ON E1.MGR = M1.EMPNO;

/*WQTD EMPLOYEE NAME, EMPLOYEE SALARY,MANAGER NAME, 
MANAGER SALARY OF A EMPLOYEE IF EMPLOYEE IS GETTING 
A SALARY MORE THAN MANAGER*/

SELECT E1.ENAME, E1.SAL, M1.ENAME, M1.SAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR = M1.EMPNO
WHERE E1.SAL>M1.SAL;


/*WQTD EMPLOYEE NAME, EMPLOYEE SALARY,MANAGER NAME, 
MANAGER SALARY OF A EMPLOYEE IF EMPLOYEE IS GETTING 
A SALARY LESS THAN MANAGER*/
SELECT E1.ENAME, E1.SAL, M1.ENAME, M1.SAL
FROM EMP E1 JOIN EMP M1
ON E1.MGR = M1.EMPNO
WHERE E1.SAL<M1.SAL;

/*WQTD  EMPLOYEE NAME, EMPLOYEE JOB, MANAGER'S NAME, MANAGER'S 
JOB IF MANAGER IS WORKING AS ANALYST*/

SELECT E1.ENAME, E1.JOB, M1.ENAME, M1.JOB
FROM EMP E1 JOIN EMP M1
ON E1.MGR = M1.EMPNO
WHERE M1.JOB='ANALYST';

SELECT * FROM EMP;

/*WQTD EMPLOYEE NAME, EMPLOYEE SALARY,
MANAGER NAME, MANAGER SALARY, MANAGER'S MANAGER NAME, 
MANAGER'S SALARY OF EMPLOYEE*/

SELECT E1.ENAME, E1.SAL, M1.ENAME, M1.SAL, M2.ENAME, M2.SAL
FROM EMP E1 JOIN EMP M1 JOIN EMP M2
ON E1.MGR = M1.EMPNO AND M1.MGR = M2.EMPNO;


/*WQTD EMPLOYEE NAME, EMPLOYEE DNAME, MANAGERS NAME, MANAGER'S DNAME IF
 EMPLOYEE & MANAGER WORK IN SAME LOCATION NEQ YORK
 THIS QUERY IS COMBINATION OF INNER JOIN AND SELF JOIN*/
 SELECT E1.ENAME, E1.DNAME, M1.ENAME, M1.DNAME
 FROM EMP E1 JOIN EMP M1
 ON E1.MGR = M1.EMPNO
 WHERE M1.ENAME
 
 SELECT * FROM EMP;
 
 /*OUTER JOIN:
 -->IT IS USED TO OBTAIN UNMATCHED RECORDS
 -->THREE TYPES
 --->1)LEFT OUTER JOIN
 --->2) RIGHT OUTER JOIN
 --->3) FULL OUTER JOIN  */
 
select * from placement;

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 




















































          
          





