/*NESTED SUBQUERY:
-->IF SUBQUERY WRITTEN INSIDE ANOTHER  SUBQUERY WE CALL IT AS NESTED SUBQUERY
--> WE CAN NEST TO 255 SUBQUERIES.
SHOW DATABASES;
DESC EMP;

/*WQTD MAXIMUM SALARY OF EMPLOYEE*/
SELECT MAX(SAL)
FROM EMP;

/*WQTD 2ND MAXIMUM SALARY OF EMPLOYEE*/
SELECT MAX(SAL)
FROM EMP
WHERE SAL < (SELECT MAX(SAL)
             FROM EMP);
             
/*WQTD 3RD MAXIMUM SALARY OF EMPLOYEE*/
SELECT MAX(SAL)
FROM EMP
WHERE SAL <(SELECT MAX(SAL)
            FROM EMP
WHERE SAL <(SELECT MAX(SAL)
             FROM EMP));
             
/*WQTD 4TH MAXIMUM SALARY OF EMPLOYEE*/
SELECT MAX(SAL)
FROM EMP
WHERE SAL <(SELECT MAX(SAL)
			FROM EMP
WHERE SAL <(SELECT MAX(SAL)
            FROM EMP
WHERE SAL <(SELECT MAX(SAL)
             FROM EMP))); 
             
             
/*WQTD 4TH MINIMUM SALARY OF EMPLOYEE*/
SELECT MIN(SAL)
FROM EMP
WHERE SAL >(SELECT MIN(SAL)
			FROM EMP
WHERE SAL >(SELECT MIN(SAL)
            FROM EMP
WHERE SAL >(SELECT MIN(SAL)
             FROM EMP))); 
             
             
/*WQTD NAME OF EMPLOYEE IF EMPLOYEE GGETTING 2ND MAXIMUM SALARY*/
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT  MAX(SAL)
             FROM EMP
             WHERE SAL<(SELECT MAX(SAL)
             FROM EMP));
             
/*WQTD 4TH MAXIMUM SALARY OF EMPLOYEE*/

SELECT MIN(SAL)
FROM EMP
WHERE SAL >(SELECT MIN(SAL)
			FROM EMP
WHERE SAL >(SELECT MIN(SAL)
            FROM EMP
WHERE SAL >(SELECT MIN(SAL)
             FROM EMP)));          
            

SELECT MAX(SAL)
FROM EMP
WHERE SAL< (SELECT MAX(SAL)
FROM EMP
WHERE SAL < (SELECT MAX(SAL)
FROM EMP
WHERE SAL <(SELECT MAX(SAL)
            FROM EMP)));
            
            
/*WQTD 2ND MINIMUM SALARY OF EMPLOYEE */
SELECT MIN(SAL)
FROM EMP
WHERE SAL >(SELECT MIN(SAL)
            FROM EMP);
            
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE GETTING 2ND MAX SALARY*/
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT  MAX(SAL)
             FROM EMP
             WHERE SAL<(SELECT MAX(SAL)
             FROM EMP));
             
SELECT ENAME
FROM emp
WHERE SAL = (SELECT MAX(SAL)
			FROM EMP
            WHERE SAL<(SELECT MAX(SAL)
            FROM EMP));
      
/*WQTD DNAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY*/
SELECT  DNAME 
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO 
                 FROM EMP 
                 WHERE SAL IN(SELECT MAX(SAL)
							FROM emp
                            WHERE SAL <(SELECT MAX(SAL)
                                        FROM emp)));
                                        
/*WQTD NAME OF EMPLOYEE WHO IS HIRED LAST*/
SELECT ENAME
FROM emp
WHERE HIREDATE IN(SELECT MAX(HIREDATE)
                  FROM EMP);


                        


             
             
             