/*RECURSIVE SQL QUERY*/
/*DISPLAY NUMBER FROM 1 TO 10 WITHOUT USING ANY IN BUILT FUNCTIONS*/
WITH RECURSIVE NUMBERS AS
    (SELECT 1 AS N
     UNION
     SELECT N + 1
     FROM  NUMBERS WHERE N<10
     )
SELECT * FROM NUMBERS;

/* FIND THE HIERARCHY OF EMPLOYEES UNDER A GIVEN MANAGER 'JONES'. */
SELECT * FROM EMP;

WITH RECURSIVE EMP_HIERARCHY AS
     (SELECT EMPNO,ENAME, MGR, 1 AS LVL
     FROM EMP WHERE ENAME='JONES'
     UNION
     SELECT E.EMPNO,E.ENAME, E.MGR, H.LVL+1 AS LVL
     from EMP_HIERARCHY H
     JOIN EMP AS E ON H.EMPNO = E.MGR
     )
SELECT * FROM EMP_HIERARCHY;




