/*SUBQUERY OPERATORS:
1)ALL
2)ANY
3)EXISTS
4)NOT EXISTS */

/* ALL OPERATORS:
-->ALL OPERATOR RETURNS TRUE IF ALL THE VALUES AT THE RHS(RIGHT HAND SIDE) SATISFY THE CONDITION. */

SELECT ENAME 
FROM EMP
WHERE SAL>ALL(SELECT SAL 
			  FROM EMP
              WHERE JOB="MANAGER");
              
              
/*WQTD NAME OF EMPLOYEE IF EMPLOYEE ARE GETTING A SALARY MORE THAN ALL THE SALESMAN*/
SELECT ENAME 
FROM EMP
WHERE SAL>ALL(SELECT SAL
              FROM EMP
              WHERE JOB='SALESMAN');
              
/*2) ANY OPERATOR:
-->ANY OPERATORS RETURNS TRUE IF ANY ONE OF THE VALUES AT THE RHS SATISFY THE CONDITION.
-->ITS WORKING LIKE A OR AND AND OPERATOR  */

/*WQTD NAME OF EMPLOYEES IF EMPLOYEES ARE GETTING A SALARY LESS THAN ANY/ATLEAST OF THE CLERK*/
SELECT ENAME
FROM emp
WHERE SAL<ANY(SELECT SAL
              FROM EMP
              WHERE JOB='CLERK');
              
/*WQTD NAME AND SALARY OF EMPLOYEE AND JOB OF EMPLOYEE IF EMPLOYEES 
ARE GETTING A SALARY LESS THAN ANY OF THE ANALYST*/
 SELECT * FROM EMP;
 
 SELECT ENAME,SAL,JOB
 FROM EMP
 WHERE SAL<ANY(SELECT SAL
               FROM emp
               WHERE JOB="ANALYST");


/*WQTD NAME OF EMPLOYEE IF EMPLOYEES ARE GETTING SALARY 
MORE THAN ALL THE SALESMAN BUT LESS THAN ALL THE MANAGER*/

SELECT ENAME
FROM EMP
WHERE SAL>ALL(SELECT SAL
              FROM EMP
              WHERE JOB='SALESMAN')
			  AND SAL<ANY(SELECT SAL 
						  FROM EMP
					      WHERE  JOB='MANAGER');
                          
/*WQTD ENAME AND DNAME OF EMPLOYEE */
SELECT ENAME, DNAME
FROM EMP
JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO;



SELECT * FROM DEPT;













